# The path of the banner (path relative to root of classpath) which could be provided by user
quarkus.banner.path=quarkus-banner.txt

##
## This section configure the HTTP layer of the application
##

# Enable or disable the HTTP request/response compression. Default is false.
# For more details, see https://quarkus.io/guides/rest#http-compression
quarkus.http.enable-compression=true

# The media types that should be compressed. Default is empty.
# For more details, see https://quarkus.io/guides/rest#http-compression
quarkus.http.compress-media-types=application/json,application/xml,text/html,text/plain

# Setting the key store file
# For default environment, the key store file is located in the resources folder
# For prod environment, the key store file is located in the /security/keystore folder
# mounted as a secret volume
quarkus.http.ssl.certificate.key-store-file=app-keystore.p12
%prod.quarkus.http.ssl.certificate.key-store-file=/security/keystore/app-keystore.p12

# Setting the key store password
# For default environment, the password is hardcoded
# For prod environment, the password is managed through a secret
# See the file src/main/kubernetes/common.yml where the secret is defined
quarkus.http.ssl.certificate.key-store-password=YXBwLWtleXN0b3JlLnAxMg==
%prod.quarkus.http.ssl.certificate.key-store-password=${APP_KEYSTORE_PASSWORD}

# Setting the key store type (PKCS12)
quarkus.http.ssl.certificate.key-store-file-type=PKCS12

# Smallrye GraphQL configuration
quarkus.smallrye-graphql.root-path=api/graphql

# H2 configuration (default)
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#quarkus.datasource.jdbc.url=jdbc:h2:tcp://localhost:9092/mem:quarkus

# ORM configuration
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=sample_data.sql
quarkus.hibernate-orm.log.sql=true

# PostgreSQL configuration (production)
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.jdbc.url=${DB_URL}
%prod.quarkus.datasource.jdbc.max-size=20
%prod.quarkus.datasource.username=${DB_USERNAME}
%prod.quarkus.datasource.password=${DB_PASSWORD}

# ORM configuration (production)
%prod.quarkus.hibernate-orm.log.sql=false

# MinIO configuration (production)
%prod.quarkus.minio.host=http://minio
%prod.quarkus.minio.port=9000
%prod.quarkus.minio.secure=false
%prod.quarkus.minio.access-key=${MINIO_USER_ACCESS_KEY}
%prod.quarkus.minio.secret-key=${MINIO_USER_SECRET_KEY}

##
## This section configure the logging
##
%dev.quarkus.log.category."it.dontesta.labs.quarkus.graphql.s3.service".level=DEBUG
%dev.quarkus.log.category."it.dontesta.labs.quarkus.graphql.app.lifecycle.s3.BookFrontBackCoverLoader".level=DEBUG
