/*
 * Copyright (c) 2025 Antonio Musarra's Blog.
 * SPDX-License-Identifier: MIT
 */
import type { EntityMetadata } from './metadata.js';
import { PanacheQuery } from './panache-query.js';
import { currentEntityManager } from './session.js';

/** A concrete mapped class: constructible, and carrying its own mapping. */
export interface EntityClass<T extends PanacheEntity> {
  new (): T;
  readonly metadata: EntityMetadata;
}

/**
 * `io.quarkus.hibernate.orm.panache.PanacheEntity`.
 *
 * Supplies the generated `id` and the active-record operations the entities
 * inherit. The static helpers take a typed `this`, which is how a TypeScript
 * subclass gets the same "`Book.listAll()` returns `Book[]`" ergonomics Java
 * gets from the generated bytecode. Each one reaches the database, so each one
 * is asynchronous — the equivalent of the blocking JDBC call the original makes
 * on its request thread.
 */
export abstract class PanacheEntity {
  id: number | null = null;

  static async listAll<T extends PanacheEntity>(this: EntityClass<T>): Promise<T[]> {
    return (await (await currentEntityManager()).listAll(this.metadata)) as unknown as T[];
  }

  static findAll<T extends PanacheEntity>(this: EntityClass<T>): PanacheQuery<T> {
    return new PanacheQuery<T>(this.metadata);
  }

  static async findById<T extends PanacheEntity>(
    this: EntityClass<T>,
    id: number | null | undefined,
  ): Promise<T | null> {
    return await (await currentEntityManager()).find<T>(this, id);
  }

  static find<T extends PanacheEntity>(
    this: EntityClass<T>,
    query: string,
    ...params: unknown[]
  ): PanacheQuery<T> {
    return new PanacheQuery<T>(this.metadata, { query, params });
  }

  static async list<T extends PanacheEntity>(
    this: EntityClass<T>,
    query: string,
    ...params: unknown[]
  ): Promise<T[]> {
    return (await (await currentEntityManager()).query(
      this.metadata,
      query,
      params,
    )) as unknown as T[];
  }

  async persist(): Promise<void> {
    await (await currentEntityManager()).persist(this);
  }

  async delete(): Promise<void> {
    (await currentEntityManager()).remove(this);
  }

  /**
   * Jackson serialises the public fields in declaration order and skips
   * anything annotated `@JsonBackReference`, which is every inverse
   * association in this model.
   */
  toJSON(): Record<string, unknown> {
    const metadata = (this.constructor as unknown as EntityClass<this>).metadata;
    const self = this as unknown as Record<string, unknown>;
    const json: Record<string, unknown> = { id: this.id };

    for (const column of metadata.columns) {
      json[column.property] = self[column.property] ?? null;
    }
    for (const collection of metadata.elementCollections) {
      json[collection.property] = self[collection.property] ?? null;
    }
    for (const association of metadata.manyToMany) {
      json[association.property] = self[association.property] ?? null;
    }
    for (const association of metadata.manyToOne) {
      json[association.property] = self[association.property] ?? null;
    }
    return json;
  }
}
